import Head from 'next/head'
import Link from 'next/link';
// import styles from '@/styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css';
import Navbar from './Components/Navbar';
import AboutComponent from './Components/AboutComponent';
import HeroComponent from './Components/HeroComponent';
import ServicesComponent from './Components/ServicesComponent';
import PortfolioComponent from './Components/PortfolioComponent';
import ContactComponent from './Components/ContactComponent';
import Footer from './Components/Footer';
import ScrollNav from './Components/ScrollNav';
import 'animate.css';
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/>
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    
  />
  <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"></link>
  <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"/>
  <script>
  AOS.init();
</script>
<script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
<script src="script.js"></script>
      </Head>
 <Navbar/>
 <ScrollNav/>
<HeroComponent/>
<AboutComponent/>
<ServicesComponent/>
<PortfolioComponent/>
<ContactComponent/>
<Footer/>
    </>
  )
}
